### ISSUE TITLE
What is `matrix_state_dir` config option used for?

### ISSUE THREAD

**Issue by Nhqml** [prologin/prololo#23]
I was wondering what is the use of config option `matrix_state_dir`? Prololo doc states that it's the *path to a directory where the bot will store Matrix state and current session information.*

However I have never seen anything in this directory and the file `matrix-session.yaml` that is created to be able to restore the session on bot reload is not stored there but in the current working directory instead.

Can someone explain what is the use of `matrix_state_dir` please?

**Comment by alarsyo** [comment]
I've never had it create anything in the state dir either, but supposedly the matrix client could store some sync state there. [The documentation](https://docs.rs/matrix-sdk/0.4.1/matrix_sdk/struct.ClientConfig.html#method.store_path) doesn't go into much detail, but I'll ask the question in the Matrix room for matrix-rust-sdk.

**Comment by alarsyo** [comment]
I've pushed with further questions and it turns out, that state store is only created if the corresponding `sled_state_store` feature is enabled, which, it is by default, but [I'd disabled all default features for `matrix_sdk`](https://github.com/prologin/prololo/blob/86a61cce57e7d2466b7273b776cd8843e5ede395/Cargo.toml#L26-L29) because we don't need most of them.
